# Generated by Django 6.1.1 on 2026-09-13 11:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_room(apps, schema_editor):
    """Set each tenancy's room from its bed's room, so the column can be NOT NULL."""
    Tenancy = apps.get_model("tenancies", "Tenancy")
    for tenancy in Tenancy.objects.select_related("bed").all():
        if tenancy.room_id is None and tenancy.bed_id is not None:
            tenancy.room_id = tenancy.bed.room_id
            tenancy.save(update_fields=["room_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='rooms.room'),
        ),
        migrations.RunPython(backfill_room, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenancy',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='rooms.room'),
        ),
    ]
